In [15]:
import numpy as np

def printDiagonalSums(mat, n):
    principal=0
    
    for i in range(0, n):
        for j in range(0, n):
 
            # Condition for principal diagonal
            if (i == j):
                principal += mat[i][j]
         
    print("Principal Diagonal:", principal)
    
    # Driver code
mat= np.array([[ 1, 2, 5, 4 ],[ 5, 6, 2, 8 ],[ 1, 2, 20, 4 ], [ 5, 6, 7, 16 ]])
matrix=mat.T
print("Transpose matrix:\n",matrix)
printDiagonalSums(matrix, 4)

Transpose matrix: 
 [[ 1  5  1  5]
 [ 2  6  2  6]
 [ 5  2 20  7]
 [ 4  8  4 16]]
Principal Diagonal: 43
